insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (1, 'Cloe', 'Biggerdike', 'cbiggerdike0@skype.com', '610-870-9446', '76616 Schurz Alley', 'Uacon', null, '1169');
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (2, 'Kissiah', 'Tubridy', 'ktubridy1@webs.com', '645-880-6919', '51201 Russell Court', 'Obispos', null, null);
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (3, 'Concordia', 'Cotesford', 'ccotesford2@parallels.com', '710-641-1260', '990 Loftsgordon Lane', 'Changning', null, null);
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (4, 'Mahala', 'MacKnockiter', 'mmacknockiter3@1und1.de', '971-416-7266', '14465 Arapahoe Drive', 'Pallasovka', null, '404264');
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (5, 'Zoe', 'Hackworthy', 'zhackworthy4@hubpages.com', '790-769-0832', '62 Emmet Center', 'Kamień Pomorski', null, '72-400');
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (6, 'Caesar', 'Domenici', 'cdomenici5@altervista.org', '579-106-2049', '60431 Oak Valley Avenue', 'Terrugem', '11', '2770-024');
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (7, 'Godard', 'Tawn', 'gtawn6@fastcompany.com', '997-294-3960', '71272 Grim Street', 'Shādegān', null, null);
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (8, 'Donaugh', 'Mebius', 'dmebius7@bloglines.com', '320-442-2080', '10 Dovetail Hill', '‘Awaj', null, null);
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (9, 'Liana', 'Coulthart', 'lcoulthart8@dmoz.org', '611-341-3286', '9 Cody Junction', 'Manquiring', null, '7104');
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (10, 'Jamey', 'Kimmince', 'jkimmince9@google.co.uk', '204-819-4671', '7 Arizona Alley', 'Huangchen', null, null);
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (11, 'Colman', 'McCrossan', 'cmccrossana@mysql.com', '724-914-0247', '8 Hanson Lane', 'Ihosy', null, null);
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (12, 'Bliss', 'Drinkhill', 'bdrinkhillb@is.gd', '712-848-9983', '59842 South Parkway', 'Sobue', null, '503-1305');
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (13, 'Greta', 'Rodrigues', 'grodriguesc@statcounter.com', '522-162-6110', '5 Melody Avenue', 'Saraktash', null, '462159');
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (14, 'Alexandros', 'Janovsky', 'ajanovskyd@infoseek.co.jp', '954-489-7081', '193 Brentwood Junction', 'Orizari', null, '2302');
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (15, 'Faye', 'Lovelock', 'flovelocke@blogspot.com', '633-240-5448', '7052 Hallows Trail', 'Meicheng', null, null);
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (16, 'Legra', 'McGarva', 'lmcgarvaf@simplemachines.org', '492-310-9656', '7420 Jenifer Trail', 'Fort-de-France', 'MQ', '97243 CEDEX');
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (17, 'Ashley', 'Dureden', 'aduredeng@surveymonkey.com', '751-830-6742', '04232 Sachtjen Circle', 'Rokiškis', null, '42001');
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (18, 'Roxine', 'Giddins', 'rgiddinsh@macromedia.com', '582-519-9357', '24 Reindahl Avenue', 'Bayrachky', null, null);
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (19, 'Raye', 'Selley', 'rselleyi@symantec.com', '691-641-3453', '573 Transport Alley', 'Châlons-en-Champagne', 'A4', '51012 CEDEX');
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (20, 'Ario', 'Gorusso', 'agorussoj@bigcartel.com', '813-383-4671', '7451 Delaware Terrace', 'Da’an', null, null);
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (21, 'Shanta', 'Oldrey', 'soldreyk@pbs.org', '507-344-4076', '75 Linden Park', 'Lais', null, '9601');
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (22, 'Rosemonde', 'Berendsen', 'rberendsenl@globo.com', '240-766-8119', '17914 Buena Vista Drive', 'Penza', null, '440999');
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (23, 'Bianca', 'Joules', 'bjoulesm@reddit.com', '329-978-4694', '87168 Ludington Alley', 'Cergy-Pontoise', 'A8', '95652 CEDEX');
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (24, 'Linnea', 'Godilington', 'lgodilingtonn@amazon.de', '133-429-0190', '08 Springs Trail', 'Nossa Senhora da Glória', null, '49680-000');
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (25, 'Waverley', 'Zannotelli', 'wzannotellio@nih.gov', '437-355-1776', '0368 Pierstorff Hill', 'Stocksund', 'AB', '182 74');
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (26, 'Lyn', 'Roskelley', 'lroskelleyp@ucla.edu', '682-613-7968', '9267 Kensington Alley', 'Jerez', null, '22010');
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (27, 'Tabby', 'Purkiss', 'tpurkissq@mediafire.com', '761-779-2429', '4875 Eagan Center', 'Kittilä', null, '99101');
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (28, 'Giulietta', 'Blagden', 'gblagdenr@globo.com', '677-699-5965', '55 Corben Junction', 'Tabūk', null, null);
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (29, 'Andria', 'Pleasaunce', 'apleasaunces@cdbaby.com', '791-670-0631', '64573 Sage Drive', 'Chornukhyne', null, null);
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (30, 'Kelsey', 'Ivashchenko', 'kivashchenkot@ox.ac.uk', '814-513-0925', '781 4th Hill', 'Kardítsa', null, null);
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (31, 'John', 'Gantzer', 'jgantzeru@nationalgeographic.com', '286-871-1618', '827 Brown Trail', 'Campo de la Cruz', null, '084047');
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (32, 'Rosalie', 'Nisen', 'rnisenv@shutterfly.com', '889-524-0304', '16 Grayhawk Junction', 'Dalu', null, null);
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (33, 'Walsh', 'Boscott', 'wboscottw@ibm.com', '911-186-7314', '7612 Eastwood Parkway', 'Bajram Curri', null, null);
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (34, 'Constantin', 'Mazzia', 'cmazziax@unesco.org', '396-348-8950', '992 Oak Valley Hill', 'Murowana Goślina', null, '62-096');
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (35, 'Christean', 'Olney', 'colneyy@netvibes.com', '131-841-7238', '0 Blaine Street', 'Dongfeng', null, null);
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (36, 'Rica', 'O''Scollain', 'roscollainz@aol.com', '897-139-0611', '8 Oxford Point', 'Trzebunia', null, '32-438');
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (37, 'Tillie', 'Cranney', 'tcranney10@4shared.com', '142-803-3104', '3570 Harper Drive', 'Emiliano Zapata', 'COL', '32883');
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (38, 'Nariko', 'Ivic', 'nivic11@umich.edu', '447-772-5480', '06558 Texas Circle', 'Bacabal', null, '65700-000');
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (39, 'Berty', 'Matthewes', 'bmatthewes12@oakley.com', '476-117-2246', '9 Forest Run Plaza', 'Binzhou', null, null);
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (40, 'Hayden', 'Treagust', 'htreagust13@buzzfeed.com', '437-243-7843', '58519 Continental Terrace', 'Agiásos', null, null);
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (41, 'Dru', 'Salvati', 'dsalvati14@army.mil', '576-469-1153', '7689 Mandrake Parkway', 'Xingou', null, null);
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (42, 'Bernarr', 'Brecher', 'bbrecher15@miitbeian.gov.cn', '290-956-8787', '0079 Westerfield Court', 'Mijiang', null, null);
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (43, 'Sammy', 'Deeman', 'sdeeman16@about.com', '833-715-6614', '3116 Pepper Wood Road', 'Liběšice', null, '506 01');
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (44, 'Fedora', 'Risebarer', 'frisebarer17@nifty.com', '606-592-2317', '3 Heath Drive', 'Frederiksberg', '1084', '1906');
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (45, 'Alfonso', 'Boylund', 'aboylund18@unc.edu', '992-193-0123', '5 Park Meadow Place', 'Nykvarn', 'AB', '155 33');
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (46, 'Faydra', 'Pollicatt', 'fpollicatt19@dot.gov', '340-957-0453', '31389 Lotheville Hill', 'Pérez', null, '2121');
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (47, 'Ysabel', 'McMillian', 'ymcmillian1a@webnode.com', '662-994-1176', '80 Butternut Alley', 'San Diego', null, '30302');
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (48, 'Hagan', 'Migheli', 'hmigheli1b@ow.ly', '303-949-0712', '306 Toban Hill', 'Xiaoshiqiao', null, null);
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (49, 'Emmalynne', 'Pitchford', 'epitchford1c@nymag.com', '251-720-4581', '93844 Buell Pass', 'Overyata', null, '617071');
insert into user (id, first_name, last_name, email, phone, streetaddress, city, province, postalcode) values (50, 'Hugh', 'Discombe', 'hdiscombe1d@photobucket.com', '240-467-6251', '1052 Mosinee Avenue', 'Hagerstown', 'MD', '21747');

insert into product (id, product_name, category_id, price, description, prod_pic) values (1, 'Skirt - 24 Foot', 1, '$3.50', 'Wine - Red, Cabernet Merlot', 'http://dummyimage.com/134x134.jpg/5fa2dd/ffffff');
insert into product (id, product_name, category_id, price, description, prod_pic) values (2, 'Sugar - Monocystal / Rock', 2, '$7.63', 'Puree - Strawberry', 'http://dummyimage.com/145x180.jpg/5fa2dd/ffffff');
insert into product (id, product_name, category_id, price, description, prod_pic) values (3, 'Wine - White, Schroder And Schyl', 3, '$7.67', 'Oil - Shortening,liqud, Fry', 'http://dummyimage.com/187x188.jpg/5fa2dd/ffffff');
insert into product (id, product_name, category_id, price, description, prod_pic) values (4, 'Carbonated Water - Raspberry', 4, '$2.77', 'Pail - 15l White, With Handle', 'http://dummyimage.com/237x211.bmp/ff4444/ffffff');
insert into product (id, product_name, category_id, price, description, prod_pic) values (5, 'Mortadella', 5, '$9.75', 'Bread - Italian Corn Meal Poly', 'http://dummyimage.com/186x185.bmp/5fa2dd/ffffff');
insert into product (id, product_name, category_id, price, description, prod_pic) values (6, 'Crackers - Melba Toast', 6, '$5.51', 'Juice - Apple, 341 Ml', 'http://dummyimage.com/172x142.jpg/cc0000/ffffff');
insert into product (id, product_name, category_id, price, description, prod_pic) values (7, 'Trout - Smoked', 7, '$6.66', 'Wine - White, Ej Gallo', 'http://dummyimage.com/160x238.bmp/5fa2dd/ffffff');
insert into product (id, product_name, category_id, price, description, prod_pic) values (8, 'Longos - Assorted Sandwich', 8, '$8.59', 'Cookies - Fortune', 'http://dummyimage.com/223x161.png/dddddd/000000');
insert into product (id, product_name, category_id, price, description, prod_pic) values (9, 'Steampan Lid', 9, '$8.95', 'Potatoes - Mini White 3 Oz', 'http://dummyimage.com/164x239.bmp/cc0000/ffffff');
insert into product (id, product_name, category_id, price, description, prod_pic) values (10, 'Lentils - Red, Dry', 10, '$2.48', 'Flower - Commercial Bronze', 'http://dummyimage.com/195x198.png/5fa2dd/ffffff');
insert into product (id, product_name, category_id, price, description, prod_pic) values (11, 'Beer - Original Organic Lager', 11, '$1.64', 'Soup Campbells Beef With Veg', 'http://dummyimage.com/207x170.bmp/ff4444/ffffff');
insert into product (id, product_name, category_id, price, description, prod_pic) values (12, 'Wine - Ruffino Chianti Classico', 12, '$3.06', 'Sprouts - Baby Pea Tendrils', 'http://dummyimage.com/127x175.png/5fa2dd/ffffff');
insert into product (id, product_name, category_id, price, description, prod_pic) values (13, 'Durian Fruit', 13, '$3.95', 'Devonshire Cream', 'http://dummyimage.com/227x184.jpg/dddddd/000000');
insert into product (id, product_name, category_id, price, description, prod_pic) values (14, 'Mustard - Individual Pkg', 14, '$1.80', 'Bread - Crusty Italian Poly', 'http://dummyimage.com/122x111.png/cc0000/ffffff');
insert into product (id, product_name, category_id, price, description, prod_pic) values (15, 'French Pastries', 15, '$3.08', 'Bagelers', 'http://dummyimage.com/226x240.bmp/ff4444/ffffff');
insert into product (id, product_name, category_id, price, description, prod_pic) values (16, 'Carroway Seed', 16, '$1.09', 'Wine - Kwv Chenin Blanc South', 'http://dummyimage.com/148x161.png/dddddd/000000');
insert into product (id, product_name, category_id, price, description, prod_pic) values (17, 'Extract - Vanilla,artificial', 17, '$7.09', 'Yoplait Drink', 'http://dummyimage.com/160x133.bmp/cc0000/ffffff');
insert into product (id, product_name, category_id, price, description, prod_pic) values (18, 'Chicken - Diced, Cooked', 18, '$7.59', 'Lettuce - Belgian Endive', 'http://dummyimage.com/112x132.bmp/5fa2dd/ffffff');
insert into product (id, product_name, category_id, price, description, prod_pic) values (19, 'Buffalo - Short Rib Fresh', 19, '$1.30', 'Pear - Packum', 'http://dummyimage.com/125x203.png/5fa2dd/ffffff');
insert into product (id, product_name, category_id, price, description, prod_pic) values (20, 'Pail With Metal Handle 16l White', 20, '$1.18', 'Gelatine Leaves - Envelopes', 'http://dummyimage.com/235x105.jpg/cc0000/ffffff');
insert into product (id, product_name, category_id, price, description, prod_pic) values (21, 'Pop Shoppe Cream Soda', 21, '$0.79', 'Turkey - Whole, Fresh', 'http://dummyimage.com/112x109.jpg/dddddd/000000');
insert into product (id, product_name, category_id, price, description, prod_pic) values (22, 'Quail Eggs - Canned', 22, '$5.08', 'Flour - Rye', 'http://dummyimage.com/230x162.png/dddddd/000000');
insert into product (id, product_name, category_id, price, description, prod_pic) values (23, 'Sugar Thermometer', 23, '$5.37', 'Cookies - Oreo, 4 Pack', 'http://dummyimage.com/105x157.png/ff4444/ffffff');
insert into product (id, product_name, category_id, price, description, prod_pic) values (24, 'Wine - Chianti Classico Riserva', 24, '$2.55', 'Broom Handle', 'http://dummyimage.com/205x208.bmp/dddddd/000000');
insert into product (id, product_name, category_id, price, description, prod_pic) values (25, 'Corn Shoots', 25, '$1.01', 'Tray - Foam, Square 4 - S', 'http://dummyimage.com/166x101.bmp/5fa2dd/ffffff');
insert into product (id, product_name, category_id, price, description, prod_pic) values (26, 'Pastry - Butterscotch Baked', 26, '$2.09', 'Limes', 'http://dummyimage.com/116x158.png/dddddd/000000');
insert into product (id, product_name, category_id, price, description, prod_pic) values (27, 'Chicken - Base, Ultimate', 27, '$6.52', 'Pasta - Agnolotti - Butternut', 'http://dummyimage.com/151x107.bmp/dddddd/000000');
insert into product (id, product_name, category_id, price, description, prod_pic) values (28, 'Energy Drink Bawls', 28, '$6.00', 'Rambutan', 'http://dummyimage.com/190x116.png/ff4444/ffffff');
insert into product (id, product_name, category_id, price, description, prod_pic) values (29, 'Bread - Flat Bread', 29, '$0.20', 'Wine - Saint Emilion Calvet', 'http://dummyimage.com/111x197.png/5fa2dd/ffffff');
insert into product (id, product_name, category_id, price, description, prod_pic) values (30, 'Kiwano', 30, '$5.08', 'Beef - Cooked, Corned', 'http://dummyimage.com/185x166.png/ff4444/ffffff');
insert into product (id, product_name, category_id, price, description, prod_pic) values (31, 'Pasta - Angel Hair', 31, '$5.39', 'Milk - Buttermilk', 'http://dummyimage.com/105x240.jpg/dddddd/000000');
insert into product (id, product_name, category_id, price, description, prod_pic) values (32, 'Wine - Port Late Bottled Vintage', 32, '$0.09', 'Hersey Shakes', 'http://dummyimage.com/234x107.jpg/cc0000/ffffff');
insert into product (id, product_name, category_id, price, description, prod_pic) values (33, 'Cheese Cloth No 100', 33, '$1.96', 'Cranberries - Fresh', 'http://dummyimage.com/168x167.png/5fa2dd/ffffff');
insert into product (id, product_name, category_id, price, description, prod_pic) values (34, 'Cheese - Brie', 34, '$4.86', 'Sproutsmustard Cress', 'http://dummyimage.com/101x131.bmp/ff4444/ffffff');
insert into product (id, product_name, category_id, price, description, prod_pic) values (35, 'Loaf Pan - 2 Lb, Foil', 35, '$9.83', 'Yeast Dry - Fleischman', 'http://dummyimage.com/134x202.jpg/5fa2dd/ffffff');
insert into product (id, product_name, category_id, price, description, prod_pic) values (36, 'Pails With Lids', 36, '$2.24', 'Container - Clear 16 Oz', 'http://dummyimage.com/105x224.png/ff4444/ffffff');
insert into product (id, product_name, category_id, price, description, prod_pic) values (37, 'Pasta - Elbows, Macaroni, Dry', 37, '$2.16', 'Nantucket Cranberry Juice', 'http://dummyimage.com/212x126.jpg/ff4444/ffffff');
insert into product (id, product_name, category_id, price, description, prod_pic) values (38, 'Steampan - Lid For Half Size', 38, '$7.76', 'Cut Wakame - Hanawakaba', 'http://dummyimage.com/225x193.bmp/ff4444/ffffff');
insert into product (id, product_name, category_id, price, description, prod_pic) values (39, 'Sausage - Liver', 39, '$5.07', 'Syrup - Monin, Swiss Choclate', 'http://dummyimage.com/194x153.bmp/dddddd/000000');
insert into product (id, product_name, category_id, price, description, prod_pic) values (40, 'Pepper - Julienne, Frozen', 40, '$0.71', 'Bread - Rolls, Rye', 'http://dummyimage.com/111x108.png/dddddd/000000');
insert into product (id, product_name, category_id, price, description, prod_pic) values (41, 'Soup - Knorr, French Onion', 41, '$5.19', 'Sage - Fresh', 'http://dummyimage.com/233x200.bmp/cc0000/ffffff');
insert into product (id, product_name, category_id, price, description, prod_pic) values (42, 'Vinegar - Balsamic', 42, '$1.52', 'Sour Puss Raspberry', 'http://dummyimage.com/231x132.bmp/ff4444/ffffff');
insert into product (id, product_name, category_id, price, description, prod_pic) values (43, 'Vacuum Bags 12x16', 43, '$7.11', 'Basil - Pesto Sauce', 'http://dummyimage.com/153x209.bmp/cc0000/ffffff');
insert into product (id, product_name, category_id, price, description, prod_pic) values (44, 'Baking Powder', 44, '$2.01', 'Oven Mitt - 13 Inch', 'http://dummyimage.com/176x204.png/dddddd/000000');
insert into product (id, product_name, category_id, price, description, prod_pic) values (45, 'Pork - Side Ribs', 45, '$4.73', 'Pasta - Gnocchi, Potato', 'http://dummyimage.com/241x182.png/5fa2dd/ffffff');
insert into product (id, product_name, category_id, price, description, prod_pic) values (46, 'Brandy - Orange, Mc Guiness', 46, '$1.32', 'Sprouts Dikon', 'http://dummyimage.com/116x225.png/cc0000/ffffff');
insert into product (id, product_name, category_id, price, description, prod_pic) values (47, 'Rabbit - Whole', 47, '$3.41', 'Wine - Toasted Head', 'http://dummyimage.com/101x167.png/5fa2dd/ffffff');
insert into product (id, product_name, category_id, price, description, prod_pic) values (48, 'Noodles - Steamed Chow Mein', 48, '$5.39', 'Lidsoupcont Rp12dn', 'http://dummyimage.com/145x211.png/5fa2dd/ffffff');
insert into product (id, product_name, category_id, price, description, prod_pic) values (49, 'Beef - Inside Round', 49, '$3.68', 'Puree - Passion Fruit', 'http://dummyimage.com/135x210.bmp/dddddd/000000');
insert into product (id, product_name, category_id, price, description, prod_pic) values (50, 'Gin - Gilbeys London, Dry', 50, '$5.88', 'Southern Comfort', 'http://dummyimage.com/149x108.png/dddddd/000000');

insert into category (id, category_name, description) values (1, 'Milk - Condensed', 'Beans - Turtle, Black, Dry');
insert into category (id, category_name, description) values (2, 'Coffee - Cafe Moreno', 'Wine - Cava Aria Estate Brut');
insert into category (id, category_name, description) values (3, 'Shrimp - Black Tiger 6 - 8', 'Potatoes - Parissienne');
insert into category (id, category_name, description) values (4, 'Soup - Campbells - Tomato', 'Wine - White, Pinot Grigio');
insert into category (id, category_name, description) values (5, 'Ginger - Ground', 'Mousse - Passion Fruit');
insert into category (id, category_name, description) values (6, 'Fish - Atlantic Salmon, Cold', 'Paper Towel Touchless');
insert into category (id, category_name, description) values (7, 'Vinegar - Champagne', 'Chips Potato Swt Chilli Sour');
insert into category (id, category_name, description) values (8, 'Plasticspoonblack', 'Sugar - Fine');
insert into category (id, category_name, description) values (9, 'Pastry - Apple Large', 'Containter - 3oz Microwave Rect.');
insert into category (id, category_name, description) values (10, 'Longos - Cheese Tortellini', 'Wine - Bouchard La Vignee Pinot');
insert into category (id, category_name, description) values (11, 'Cod - Salted, Boneless', 'Bread Base - Goodhearth');
insert into category (id, category_name, description) values (12, 'Garlic - Primerba, Paste', 'Cup - 4oz Translucent');
insert into category (id, category_name, description) values (13, 'Nestea - Ice Tea, Diet', 'Salmon - Canned');
insert into category (id, category_name, description) values (14, 'Oil - Canola', 'Dried Cherries');
insert into category (id, category_name, description) values (15, 'Raisin - Golden', 'Fudge - Cream Fudge');
insert into category (id, category_name, description) values (16, 'Ice Cream - Strawberry', 'Corn - Mini');
insert into category (id, category_name, description) values (17, 'Flour - So Mix Cake White', 'Sobe - Orange Carrot');
insert into category (id, category_name, description) values (18, 'Chinese Foods - Cantonese', 'Lid Tray - 12in Dome');
insert into category (id, category_name, description) values (19, 'Juice - Cranberry 284ml', 'Table Cloth 54x72 Colour');
insert into category (id, category_name, description) values (20, 'Chips - Miss Vickies', 'Plasticspoonblack');